version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py

# formats: all

# python:
#   version: 3.7
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - all
#     - requirements: docs/requirements_docs.txt
#   system_packages: true

submodules:
  include: all
