version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

# conda:
#   environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py

# formats: all

# python:
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - all
#     - requirements: docs/requirements_docs.txt
#   system_packages: true

submodules:
  include: all
