# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test executables and lint

on:
  push:
    branches:
      - main
      - examples
  pull_request:
    branches:
      - main
      - examples

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage pytest-xdist nbmake pytest-cov
        pip install .
        python -m ipykernel install --user --name ringdown
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit tests
      run: |
        # Run the unit tests
        pytest -n=auto --cov=ringdown --cov-report=xml
    - name: Test fit
      run: |
        # test config file interface
        bash tests/test_fit_config.sh
    - name: Test pipe
      run: |
        # test pipe
        bash tests/test_pipe_config.sh
    - name: Test scan
      run: |
        # test scan
        bash tests/test_scan_config.sh
